'use strict';
(()=>{
const $=id=>document.getElementById(id), ID=/^[a-f0-9]{32}$/, SHA=/^[a-f0-9]{64}$/;
const profileIDs=new Set(); let uploadLimit=0, selected='', timer=0;
function notice(s){$('notice').textContent=s} function el(tag,text,cls){const x=document.createElement(tag);x.textContent=text;if(cls)x.className=cls;return x}
async function api(path,options={}){const response=await fetch('/api'+path,{...options,credentials:'omit',redirect:'error',cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);if(response.status===204)return null;const type=response.headers.get('content-type')?.split(';')[0];if(type!=='application/json')throw new Error('Invalid response');return response.json()}
function validJob(j){if(!j||!ID.test(j.id)||typeof j.name!=='string'||typeof j.status!=='string'||!Array.isArray(j.artifacts)||j.failure_code&&!['media_type_mismatch','job_failed'].includes(j.failure_code))throw new Error('Invalid job');return j}
function failureMessage(j){if(j.status!=='failed')return '';return j.failure_code==='media_type_mismatch'?'File contents do not match the filename extension. Convert the original to a real WAV or M4A file, then upload the converted file.':'Processing failed. The original upload was retained; inspect the job before retrying.'}
async function mediaProblem(file,extension){const b=new Uint8Array(await file.slice(0,12).arrayBuffer()),ascii=(a,z)=>String.fromCharCode(...b.slice(a,z)),wav=b.length>=12&&ascii(0,4)==='RIFF'&&ascii(8,12)==='WAVE',mp4=b.length>=12&&ascii(4,8)==='ftyp',mp3=b.length>=3&&ascii(0,3)==='ID3'||b.length>=2&&b[0]===255&&(b[1]&224)===224;if(extension==='wav'&&!wav)return mp3?'This file contains MP3 audio but is named .wav. Convert it to WAV or M4A, then upload the converted file.':'This file is named .wav but does not contain WAV audio. Convert it to WAV or M4A, then try again.';if(extension==='m4a'&&!mp4)return wav?'This file contains WAV audio but is named .m4a. Rename it to .wav or convert it to M4A, then try again.':'This file is named .m4a but does not contain M4A audio. Convert it to WAV or M4A, then try again.';return ''}
async function profiles(){const x=await api('/v1/profiles');if(!Array.isArray(x.profiles)||!Number.isSafeInteger(x.max_upload_bytes))throw new Error('Invalid profiles');x.profiles.forEach(p=>profileIDs.add(p));uploadLimit=x.max_upload_bytes;$('limit').textContent='Maximum upload: '+Math.round(uploadLimit/1048576)+' MiB.'}
async function queue(){const x=await api('/v1/queue');const map=new Map((x.entries||[]).map(e=>[e.job_id,e]));return map}
async function list(){try{const [page,q]=await Promise.all([api('/v1/jobs'),queue()]);$('jobs').replaceChildren();let active=false;for(const raw of page.jobs||[]){const j=validJob(raw),entry=q.get(j.id);if(entry&&['pending','running'].includes(entry.status))active=true;const box=el('article','', 'job'),body=document.createElement('div');body.append(el('p',j.name),el('p',j.id,'id'),el('p',(entry?.status||j.status)+(j.active_stage?' · '+j.active_stage:''),'badge'));const reason=failureMessage(j);if(reason)body.append(el('p',reason,'error'));const b=el('button','Inspect');b.type='button';b.onclick=()=>inspect(j.id);box.append(body,b);$('jobs').append(box)}notice(active?'A job is queued or running.':'Ready.');if(selected)await inspect(selected,false);schedule(active?2000:8000)}catch(e){notice('Refresh failed: '+e.message);schedule(5000)}}
function schedule(ms){clearTimeout(timer);timer=setTimeout(list,ms)}
async function inspect(id,scroll=true){try{const [j,q]=await Promise.all([api('/v1/jobs/'+id),queue()]);validJob(j);selected=id;$('detail').hidden=false;$('metadata').replaceChildren();const entry=q.get(id),reason=failureMessage(j);for(const [k,v] of [['Name',j.name],['ID',j.id],['Profile',j.profile],['Job status',j.status],['Queue status',entry?.status||'not queued'],['Stage',j.active_stage||'—'],['Attempts',String(j.attempts)],...(reason?[['What happened',reason]]:[])])$('metadata').append(el('dt',k),el('dd',v));$('actions').replaceChildren();const terminal=entry&&['failed','cancelled','interrupted'].includes(entry.status),permanent=j.failure_code==='media_type_mismatch';if(!permanent&&(!entry||terminal)){const b=el('button',terminal?'Retry':'Queue');b.onclick=()=>enqueue(id,!!terminal);$('actions').append(b)}if(entry&&['pending','running'].includes(entry.status)){const b=el('button','Cancel');b.onclick=()=>cancel(id);$('actions').append(b)}const del=el('button','Delete','danger');del.onclick=()=>remove(id);$('actions').append(del);$('downloads').replaceChildren();for(const a of j.artifacts){if(!['transcript','vtt','speaker-transcript','speaker-vtt'].includes(a.name)||!SHA.test(a.sha256))continue;const b=el('button','Download '+a.name);b.onclick=()=>download(j,a);$('downloads').append(b)}if(scroll)$('detail').scrollIntoView({behavior:'smooth'})}catch(e){notice('Inspect failed: '+e.message)}}
async function enqueue(id,retry){try{await api('/v1/jobs/'+id+'/'+(retry?'retry-queued':'enqueue'),{method:'POST'});notice(retry?'Retry queued.':'Job queued.');await list()}catch(e){notice('Queue failed: '+e.message)}}
async function cancel(id){try{await api('/v1/jobs/'+id+'/cancel',{method:'POST'});notice('Cancellation requested.');await list()}catch(e){notice('Cancel failed: '+e.message)}}
async function remove(id){if(!confirm('Permanently delete this job, media and transcripts?'))return;try{await api('/v1/jobs/'+id,{method:'DELETE'});selected='';$('detail').hidden=true;notice('Deleted.');await list()}catch(e){notice('Delete failed: '+e.message)}}
async function download(j,a){try{const fresh=validJob(await api('/v1/jobs/'+j.id)),meta=fresh.artifacts.find(x=>x.name===a.name);if(!meta||meta.sha256!==a.sha256)throw new Error('Artifact changed');const r=await fetch('/api/v1/jobs/'+j.id+'/artifacts/'+a.name,{cache:'no-store',credentials:'omit',redirect:'error'});if(!r.ok||r.headers.get('etag')!=='"sha256-'+a.sha256+'"')throw new Error('Artifact verification failed');const blob=await r.blob();if(blob.size!==a.bytes)throw new Error('Artifact length changed');const u=URL.createObjectURL(blob),link=document.createElement('a');link.href=u;link.download=j.id+'-'+a.name+(a.name.includes('vtt')?'.vtt':'.json');document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}catch(e){notice('Download failed: '+e.message)}}
$('upload').onsubmit=async event=>{event.preventDefault();const file=$('file').files[0],language=$('language').value,extension=file?.name.toLowerCase().endsWith('.m4a')?'m4a':file?.name.toLowerCase().endsWith('.wav')?'wav':'';if(!file||!extension||file.size<1||file.size>uploadLimit){notice('Choose a non-empty M4A or WAV within the limit.');return}$('submit').disabled=true;try{const problem=await mediaProblem(file,extension);if(problem){notice(problem);return}const profile=($('diarize').checked?'diar':'asr')+'-'+language+'-'+extension;if(!profileIDs.has(profile)){notice('Selected profile is unavailable.');return}const params=new URLSearchParams({profile,name:file.name}),job=validJob(await api('/v1/jobs?'+params,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file}));await api('/v1/jobs/'+job.id+'/enqueue',{method:'POST'});$('file').value='';selected=job.id;notice('Upload acknowledged and queued.');await list();await inspect(job.id)}catch(e){notice('Upload may be retained; inspect jobs before retrying. '+e.message)}finally{$('submit').disabled=false}};
$('refresh').onclick=list;window.addEventListener('pagehide',()=>clearTimeout(timer));
(async()=>{try{await profiles();await list()}catch(e){notice('Service unavailable: '+e.message)}})();
})();
