'use strict';
(()=>{
const $=id=>document.getElementById(id),ID=/^[a-f0-9]{32}$/,SHA=/^[a-f0-9]{64}$/,FAILURES=new Set(['media_type_mismatch','job_failed']);
const profileIDs=new Set();let uploadLimit=0,selected='',timer=0,current=null,progressStream=null;const work=new Map();
function notice(s){$('notice').textContent=s}function el(tag,text,cls){const x=document.createElement(tag);x.textContent=text;if(cls)x.className=cls;return x}
async function api(path,options={}){const response=await fetch('/api'+path,{...options,credentials:'omit',redirect:'error',cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);if(response.status===204)return null;if(response.headers.get('content-type')?.split(';')[0]!=='application/json')throw new Error('Invalid response');return response.json()}
function validJob(j){if(!j||!ID.test(j.id)||typeof j.name!=='string'||typeof j.title!=='string'||typeof j.language!=='string'||typeof j.speaker_labels!=='boolean'||typeof j.status!=='string'||j.failure_code&&!FAILURES.has(j.failure_code)||!Array.isArray(j.artifacts))throw new Error('Invalid recording');for(const a of j.artifacts)if(!a||!['transcript','vtt','speaker-transcript','speaker-vtt'].includes(a.name)||typeof a.filename!=='string'||!SHA.test(a.sha256))throw new Error('Invalid export');return j}
function failureMessage(j){if(j.status!=='failed')return'';return j.failure_code==='media_type_mismatch'?'File contents do not match the filename extension. Convert the original to a real WAV or M4A file, then upload the converted file.':'Processing failed. The original audio is still available for retry.'}
async function mediaProblem(file,extension){const b=new Uint8Array(await file.slice(0,12).arrayBuffer()),ascii=(a,z)=>String.fromCharCode(...b.slice(a,z)),wav=b.length>=12&&ascii(0,4)==='RIFF'&&ascii(8,12)==='WAVE',mp4=b.length>=12&&ascii(4,8)==='ftyp',mp3=b.length>=3&&ascii(0,3)==='ID3'||b.length>=2&&b[0]===255&&(b[1]&224)===224;if(extension==='wav'&&!wav)return mp3?'This file contains MP3 audio but is named .wav. Convert it to WAV or M4A, then upload the converted file.':'This file is named .wav but does not contain WAV audio. Convert it to WAV or M4A, then try again.';if(extension==='m4a'&&!mp4)return wav?'This file contains WAV audio but is named .m4a. Rename it to .wav or convert it to M4A, then try again.':'This file is named .m4a but does not contain M4A audio. Convert it to WAV or M4A, then try again.';return''}
function profileInfo(j){const p=j.profile.split('-'),language={auto:'Automatic language',en:'English',pt:'Portuguese',fr:'French',es:'Spanish',it:'Italian'}[j.language]||j.language||'Unknown';return{language,speakers:j.speaker_labels,format:(p[2]||j.name.split('.').pop()||'').toUpperCase()}}
function friendlyState(j,e){if(e?.status==='pending')return['Waiting','Waiting for earlier recordings'];if(e?.status==='running'){const states={decode:['Preparing audio','Checking and converting the recording'],'asr-windows':['Transcribing','Recognising speech'],'transcript':['Finalising transcript','Building readable text'],vtt:['Finalising transcript','Preparing subtitle export'],diarization:['Identifying speakers','Separating anonymous speakers'],'speaker-transcript':['Finalising speakers','Assigning words to speakers'],'speaker-vtt':['Finalising speakers','Preparing speaker subtitle export']};return states[j.active_stage]||['Processing','Working on this recording']}if(e?.status==='interrupted')return['Interrupted','Use Retry to continue'];if(j.status==='failed')return['Needs attention',failureMessage(j)];if(j.status==='complete')return['Ready',j.media_released?'Transcript saved; source audio released':'Transcript saved'];if(j.status==='cancelled')return['Cancelled','This recording was cancelled'];return['Not queued','Ready to process']}
function dateText(value){const d=new Date(value);return Number.isNaN(d.valueOf())?'':new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(d)}
function button(label,fn,cls=''){const b=el('button',label,cls);b.type='button';b.onclick=fn;return b}
async function profiles(){const x=await api('/v1/profiles');if(!Array.isArray(x.profiles)||!Number.isSafeInteger(x.max_upload_bytes))throw new Error('Invalid profiles');x.profiles.forEach(p=>profileIDs.add(p));uploadLimit=x.max_upload_bytes;$('limit').textContent='WAV or M4A · up to '+Math.round(uploadLimit/1048576)+' MiB'}
async function queue(){const x=await api('/v1/queue');return new Map((x.entries||[]).map(e=>[e.job_id,e]))}
function progressText(p){if(!p?.work||!Number.isSafeInteger(p.work.completed)||!Number.isSafeInteger(p.work.total)||p.work.total<1||p.work.completed<0||p.work.completed>p.work.total)return null;const w=p.work;if(!['asr-windows','diarization'].includes(w.stage))return null;if(w.phase==='samples')return{label:'Identifying speakers · '+Math.floor(w.completed/16000)+' / '+Math.ceil(w.total/16000)+' seconds ('+Math.floor(100*w.completed/w.total)+'%)',completed:w.completed,total:w.total};if(w.phase==='postprocess')return{label:'Analysing speakers',completed:w.completed,total:w.total};const stage=w.stage==='asr-windows'?'Transcribing':'Identifying speakers';return{label:stage+' · '+w.completed+' of '+w.total+' windows ('+Math.floor(100*w.completed/w.total)+'%)',completed:w.completed,total:w.total}}
function progressElement(p){const x=progressText(p);if(!x)return null;const holder=el('div','','progress'),label=el('span',x.label,'progress-label'),bar=document.createElement('progress');bar.max=x.total;bar.value=x.completed;bar.setAttribute('aria-label',x.label);holder.append(label,bar);return holder}
function updateProgressUI(id){const p=work.get(id),node=document.querySelector('[data-progress="'+id+'"]');if(node){const display=progressElement(p);node.replaceChildren(...(display?[display]:[]));const pill=node.parentElement.querySelector('.pill');if(pill)pill.hidden=!!display}if(selected===id){const display=progressElement(p);$('detail-progress').replaceChildren(...(display?[display]:[]));$('detail-status').hidden=!!display}}
function closeProgress(){if(progressStream){progressStream.close();progressStream=null}}
async function pollProgress(id){try{const p=await api('/v1/jobs/'+id+'/progress');if(p.job_id===id&&p.status==='running'){work.set(id,p);updateProgressUI(id)}}catch{}}
function followProgress(id){closeProgress();if(!id||!window.EventSource)return;const stream=new EventSource('/api/v1/jobs/'+id+'/progress');stream.jobID=id;progressStream=stream;stream.addEventListener('progress',event=>{if(progressStream!==stream)return;try{const p=JSON.parse(event.data);if(p.job_id!==id||!['asr-windows','diarization'].includes(p.work?.stage)&&p.work!=null)return;work.set(id,p);updateProgressUI(id);if(p.status!=='running'){stream.close();if(progressStream===stream)progressStream=null;list()}}catch{}});stream.onerror=()=>{if(progressStream===stream){stream.close();progressStream=null}}}

function renderRow(j,e,active){const info=profileInfo(j),state=friendlyState(j,e),box=el('article','',active?'recording active':'recording'),body=document.createElement('div'),top=el('div','', 'recording-title');const display=active?progressElement(work.get(j.id)):null,status=el('span',state[0],'pill');status.hidden=!!display;top.append(el('h3',j.title),status);body.append(top,el('p',[dateText(j.created),info.language,info.speakers?'Speaker labels':'Transcript only',Math.round(j.input_bytes/1024)+' KiB'].filter(Boolean).join(' · '),'summary'));if(j.status==='failed')body.append(el('p',failureMessage(j),'error'));if(active){const holder=el('div','','');holder.dataset.progress=j.id;if(display)holder.append(display);body.append(holder)}const controls=el('div','', 'row-actions');if(j.status==='complete'){const a=primaryArtifact(j);if(a)controls.append(button(primaryLabel(a),()=>download(j,a),'primary'))}controls.append(button('Open',()=>inspect(j.id),'quiet'));box.append(body,controls);return box}
function primaryArtifact(j){return j.artifacts.find(a=>a.name==='speaker-vtt')||j.artifacts.find(a=>a.name==='vtt')||j.artifacts.find(a=>a.name==='speaker-transcript')||j.artifacts.find(a=>a.name==='transcript')}
function primaryLabel(a){return a.name.startsWith('speaker-')?'Download speaker transcript':'Download transcript'}
async function list(){try{const[page,q]=await Promise.all([api('/v1/jobs'),queue()]),jobs=(page.jobs||[]).map(validJob).sort((a,b)=>new Date(b.created)-new Date(a.created));$('active').replaceChildren();$('library').replaceChildren();let active=0,library=0;for(const j of jobs){const e=q.get(j.id),isActive=e&&['pending','running'].includes(e.status);if(isActive){$('active').append(renderRow(j,e,true));active++}else{$('library').append(renderRow(j,e,false));library++}}$('active-section').hidden=!active;$('empty').hidden=!!library;if($('notice').textContent==='Connecting…')notice('');const running=jobs.find(j=>q.get(j.id)?.status==='running');if(running?.id!==progressStream?.jobID)followProgress(running?.id||'');for(const id of work.keys())if(!jobs.some(j=>j.id===id&&q.get(id)?.status==='running'))work.delete(id);if(running&&!progressStream)await pollProgress(running.id);if(selected)await inspect(selected,false);schedule(active?5000:8000)}catch(e){notice('Could not refresh recordings. '+e.message);schedule(5000)}}
function schedule(ms){clearTimeout(timer);timer=setTimeout(list,ms)}
function technical(j){const info=profileInfo(j);return[['Original file',j.name],['Added',dateText(j.created)],['Language',info.language],['Mode',info.speakers?'Transcript with speaker labels':'Transcript only'],['Format',info.format],['Size',j.input_bytes.toLocaleString()+' bytes'],['Recording ID',j.id],['Processing profile',j.profile]]}
async function inspect(id,scroll=true){try{const[j,q]=await Promise.all([api('/v1/jobs/'+id),queue()]);validJob(j);current=j;selected=id;const e=q.get(id),state=friendlyState(j,e),reason=failureMessage(j);$('detail').hidden=false;$('detail-title').textContent=j.title;$('title').value=j.title;$('title').disabled=!!(e&&['pending','running'].includes(e.status));$('rename').querySelector('button').disabled=$('title').disabled;$('detail-status').textContent=state[0]+(j.status==='failed'?'':state[1]?' · '+state[1]:'');const display=progressElement(work.get(id));$('detail-status').hidden=!!display;$('detail-progress').replaceChildren(...(display?[display]:[]));$('detail-error').hidden=!reason;$('detail-error').textContent=reason;$('metadata').replaceChildren();for(const[k,v]of technical(j))$('metadata').append(el('dt',k),el('dd',v));$('primary').replaceChildren();const primary=primaryArtifact(j);if(primary)$('primary').append(button(primaryLabel(primary),()=>download(j,primary),'primary'));$('exports').replaceChildren();for(const a of j.artifacts)if(a!==primary)$('exports').append(button(exportLabel(a.name),()=>download(j,a),'quiet'));$('export-section').hidden=!$('exports').childElementCount;$('actions').replaceChildren();const terminal=e&&['failed','cancelled','interrupted'].includes(e.status),permanent=j.failure_code==='media_type_mismatch';if(!permanent&&!j.media_released&&(!e||terminal)&&j.status!=='complete'&&j.status!=='running'){const retry=j.status==='failed'||j.status==='cancelled'||!!terminal;$('actions').append(button(retry?'Retry processing':'Start processing',()=>enqueue(id,retry)))}if(e&&['pending','running'].includes(e.status))$('actions').append(button('Cancel processing',()=>cancel(id),'quiet'));if(permanent)$('actions').append(button('Choose corrected file',chooseReplacement,'quiet'));$('actions').append(button('Delete recording',()=>remove(id),'danger'));if(scroll)$('detail').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){notice('Could not open recording. '+e.message)}}
function exportLabel(name){return name==='transcript'?'Transcript data':name==='vtt'?'Transcript subtitles':name==='speaker-transcript'?'Speaker data':'Speaker subtitles'}
async function rename(){const title=$('title').value.trim();if(!current||!title)return;try{const j=validJob(await api('/v1/jobs/'+current.id+'/title',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title})}));current=j;notice('Title saved.');await list()}catch(e){notice('Could not save title. '+e.message)}}
async function enqueue(id,retry){try{await api('/v1/jobs/'+id+'/'+(retry?'retry-queued':'enqueue'),{method:'POST'});notice(retry?'Retry queued.':'Recording queued.');await list()}catch(e){notice('Could not queue recording. '+e.message)}}
async function cancel(id){try{await api('/v1/jobs/'+id+'/cancel',{method:'POST'});notice('Cancellation requested.');await list()}catch(e){notice('Could not cancel recording. '+e.message)}}
async function remove(id){if(!confirm('Delete this recording and all of its transcripts?'))return;try{await api('/v1/jobs/'+id,{method:'DELETE'});selected='';current=null;$('detail').hidden=true;notice('Recording deleted.');await list()}catch(e){notice('Could not delete recording. '+e.message)}}
function chooseReplacement(){if(current){const p=current.profile.split('-');if(p.length===3){$('language').value=p[1];$('diarize').checked=p[0]==='diar'||p[0]==='nem';if(p[0]==='diar'||p[0]==='nem')$('speaker-provider').value=p[0]}}$('detail').hidden=true;selected='';current=null;$('file').focus();$('file').click();window.scrollTo({top:0,behavior:'smooth'})}
async function download(j,a){try{const fresh=validJob(await api('/v1/jobs/'+j.id)),meta=fresh.artifacts.find(x=>x.name===a.name);if(!meta||meta.sha256!==a.sha256||meta.filename!==a.filename)throw new Error('Export changed');const r=await fetch('/api/v1/jobs/'+j.id+'/artifacts/'+a.name,{cache:'no-store',credentials:'omit',redirect:'error'});if(!r.ok||r.headers.get('etag')!=='"sha256-'+a.sha256+'"')throw new Error('Export verification failed');const blob=await r.blob();if(blob.size!==a.bytes)throw new Error('Export length changed');const bytes=await blob.arrayBuffer();if(window.isSecureContext&&crypto.subtle){const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(digest!==a.sha256)throw new Error('Export hash changed')}const u=URL.createObjectURL(new Blob([bytes],{type:blob.type})),link=document.createElement('a');link.href=u;link.download=a.filename;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(u),30000);notice('Downloaded '+a.filename+'.')}catch(e){notice('Could not download transcript. '+e.message)}}
$('upload').onsubmit=async event=>{event.preventDefault();const file=$('file').files[0],language=$('language').value,extension=file?.name.toLowerCase().endsWith('.m4a')?'m4a':file?.name.toLowerCase().endsWith('.wav')?'wav':'';if(!file||!extension||file.size<1||file.size>uploadLimit){notice('Choose a non-empty WAV or M4A file within the limit.');return}$('submit').disabled=true;try{const problem=await mediaProblem(file,extension);if(problem){notice(problem);return}const profile=($('diarize').checked?$('speaker-provider').value:'asr')+'-'+language+'-'+extension;if(!profileIDs.has(profile)){notice('That transcription option is unavailable.');return}const params=new URLSearchParams({profile,name:file.name}),job=validJob(await api('/v1/jobs?'+params,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file}));await api('/v1/jobs/'+job.id+'/enqueue',{method:'POST'});$('file').value='';selected=job.id;notice('Recording added. Transcription has started.');await list();await inspect(job.id)}catch(e){notice('The upload may have been retained. Refresh before trying again. '+e.message)}finally{$('submit').disabled=false}};
$('rename').onsubmit=e=>{e.preventDefault();rename()};$('refresh').onclick=list;$('close-detail').onclick=()=>{$('detail').hidden=true;selected='';current=null};window.addEventListener('pagehide',()=>{clearTimeout(timer);closeProgress()});
(async()=>{try{await profiles();await list()}catch(e){notice('Service unavailable. '+e.message)}})();
})();
