package config

import "os"

var Q4kScaledLoopOn = os.Getenv("IME2_Q4K_SCALED_LOOP") != "0"
var Q4kLlamaZPOn = os.Getenv("IME2_Q4K_LLAMA_ZP") != ""
var Q4kCompareOn = os.Getenv("IME2_Q4K_COMPARE") != ""
var Q4kGoAsmSerialOn = os.Getenv("IME2_Q4K_GOASM_SERIAL") != ""
var Q4kGoAsmOn = os.Getenv("IME2_Q4K_GOASM") != ""
var Q4kCShimOn = os.Getenv("IME2_Q4K_CSHIM") != ""
var Q4kLlamaX32RefOn = os.Getenv("IME2_Q4K_LLAMA_X32_REF") != ""
var Q4kExactOn = os.Getenv("IME2_Q4K_EXACT") != ""
var Q4kBatchOn = os.Getenv("IME2_Q4K_NO_BATCH") == ""
var Q4kTCMBWaveOn = os.Getenv("IME2_TCM_B_WAVE") != ""
var Q4kTCMBWaveSingleOn = os.Getenv("IME2_TCM_B_WAVE_SINGLE") != ""
var Q4kTCMBWaveBatchOn = Q4kTCMBWaveOn && os.Getenv("IME2_TCM_B_WAVE_BATCH") != "0"
var Q4kTCMBWaveGateOn = Q4kTCMBWaveOn && os.Getenv("IME2_TCM_B_WAVE_GATE") != "0"
var Q4kGateFuseOn = os.Getenv("IME2_Q4K_GATE_FUSE") != "0"
var Q4kFFNFuseOn = os.Getenv("IME2_Q4K_FFN_FUSE") != ""
var NativeI8I8On = os.Getenv("IME2_NATIVE_I8I8") != ""
var NativeI8I8WVOn = NativeI8I8On || os.Getenv("IME2_NATIVE_I8I8_WV") != ""
var NativeI8I8DownOn = NativeI8I8On || os.Getenv("IME2_NATIVE_I8I8_DOWN") != ""
var NativeI8I8LMOn = NativeI8I8On || os.Getenv("IME2_NATIVE_I8I8_LM") != ""
var Int8DownAddOn = os.Getenv("IME2_INT8_DOWN_ADD") != "0"
var Q8RoundOn = os.Getenv("IME2_Q8_ROUND") != "0"
var Q8RVVOn = os.Getenv("IME2_Q8_RVV") != ""
var Q4kNativeCGOOn = os.Getenv("IME2_Q4K_NATIVE_CGO") != ""
