#!/usr/bin/env bash
set -euo pipefail
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
nvcc=${NVCC:-/usr/local/cuda/bin/nvcc}
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
"$nvcc" -ptx -O3 --fmad=false -arch=compute_86 "$root/scripts/kernels/mojev.cu" -o "$tmp/mojev.ptx"
{
  printf '// Code generated by scripts/generate-mojev-ptx.sh; CUDA 12.8, sm_86; DO NOT EDIT.\npackage ptx\n\nconst MoJev = `'
  cat "$tmp/mojev.ptx"
  printf '`\n'
} > "$root/backends/nvidia/ptx/mojev_generated.go"
gofmt -w "$root/backends/nvidia/ptx/mojev_generated.go"
