import{test,expect}from'bun:test';import{mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{createHash}from'node:crypto';import{generateFinal}from'./jevlike-final-requests';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
test('final selection needs freeze, all rows and hashes; preserves normal rendering',()=>{
 const root=mkdtempSync(join(tmpdir(),'jev-final-'));try{
 mkdirSync(join(root,'data'));const cases=[{context:'Task: science\nQuestion: Ice?\nAnswer:',options:['solid','gas'],label:0},{context:'Task: inference\nPremise: Ada lives in Lisbon.\nHypothesis: Ada lives in Portugal.\nAnswer:',options:['entailed','contradicted','unknown'],label:0},{context:'Task: intent\nUtterance: hello\nIntent:',options:['greeting','oos'],label:0}];const test=cases.map(JSON.stringify).join('\n')+'\n';const prov=cases.map((_,i)=>JSON.stringify({partition:'test',output_row:i+1,input:i,source_id:'row-'+i})).join('\n')+'\n';const manifest=JSON.stringify({inputs:[{source:'ai2_arc',config:'ARC-Easy'},{source:'multi_nli'},{source:'clinc_oos',config:'plus'}],artifacts:[{path:'test.jsonl',sha256:hash(test)},{path:'provenance.jsonl',sha256:hash(prov)}]});
 for(const [p,b]of Object.entries({'test.jsonl':test,'provenance.jsonl':prov,'manifest.json':manifest}))writeFileSync(join(root,'data',p),b);
 const freeze={version:1,scope:'final-once-normal-v1',expected_examples:3,dataset:'data',dataset_sha256:hash(manifest),partition_sha256:hash(test),files:{'data/manifest.json':hash(manifest)}};const path=join(root,'freeze.json');writeFileSync(path,JSON.stringify(freeze));
 const out=join(root,'out');expect(generateFinal(path,out,root).requests).toBe(3);const rows=readFileSync(join(out,'requests.jsonl'),'utf8').trim().split('\n').map(JSON.parse);expect(rows.every(r=>r.variant==='normal')).toBe(true);expect(rows.find(r=>r.task==='multi_nli').request.question).toBe('Given the evidence, classify this hypothesis: Ada lives in Portugal.');expect(rows.find(r=>r.task==='clinc_oos/plus').request.evidence).toBe('hello');expect(rows.find(r=>r.task==='ai2_arc/ARC-Easy').request.question).toBe('Ice?');expect(()=>generateFinal(path,out,root)).toThrow('output exists');
 writeFileSync(path,JSON.stringify({...freeze,scope:'other'}));expect(()=>generateFinal(path,join(root,'bad'),root)).toThrow('freeze');writeFileSync(path,JSON.stringify({...freeze,expected_examples:4}));expect(()=>generateFinal(path,join(root,'bad'),root)).toThrow('count');writeFileSync(path,JSON.stringify(freeze));writeFileSync(join(root,'data','test.jsonl'),test+'\n');expect(()=>generateFinal(path,join(root,'bad'),root)).toThrow('identity');
 }finally{rmSync(root,{recursive:true,force:true})}
});
