"""Pin full JFK RNNT greedy decisions from released PyTorch encoder.

These 139 projected encoder rows are generated by PyTorch; this does not
validate a native long-window encoder, streaming scheduler, or WER.
"""
import argparse
import gzip
import json
from pathlib import Path

import soundfile as sf
import torch
from transformers import AutoModelForRNNT, AutoProcessor
from transformers.models.nemotron3_5_asr.generation_nemotron3_5_asr import Nemotron3_5AsrRNNTDecoderCache

ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / "checkpoints/nemotron/asr"


def save(path, tensor):
    values = tensor.detach().cpu().contiguous().numpy().astype("<f4", copy=False)
    with path.open("wb") as out:
        with gzip.GzipFile(filename="", fileobj=out, mode="wb", mtime=0) as compressed:
            compressed.write(values.tobytes())
    print(path.name, values.shape)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    torch.set_num_threads(4)
    model = AutoModelForRNNT.from_pretrained(MODEL, local_files_only=True).eval()
    processor = AutoProcessor.from_pretrained(MODEL, local_files_only=True)
    audio, rate = sf.read(ROOT / "testdata/jfk.wav", dtype="float32")
    if rate != 16000 or len(audio) != 176000:
        raise ValueError("unexpected JFK waveform")
    processed = processor(audio, sampling_rate=rate, return_tensors="pt")
    with torch.inference_mode():
        output = model.get_audio_features(
            input_features=processed.input_features,
            attention_mask=processed.attention_mask,
            num_lookahead_tokens=3,
            prompt_ids=torch.tensor([model.config.default_prompt_id]),
        )
        encoder = output.pooler_output
        if encoder.shape != (1, 139, 640):
            raise ValueError(f"unexpected projected shape {encoder.shape}")
        save(args.out / "asr_jfk_full_encoder.f32.gz", encoder[0])
        cache = Nemotron3_5AsrRNNTDecoderCache(model.config)
        frame, token, symbols = 0, model.config.blank_token_id, 0
        tokens, frames, selected_logits, runner_tokens, runner_logits, margins = [], [], [], [], [], []
        while frame < encoder.shape[1]:
            predictor = model.decoder(torch.tensor([[token]]), cache=cache)
            logits = model.joint(encoder[:, frame:frame+1, None, :], predictor[:, None, :, :]).reshape(-1)
            top = torch.topk(logits, 2)
            selected_logits.append(float(top.values[0]))
            runner_tokens.append(int(top.indices[1]))
            runner_logits.append(float(top.values[1]))
            margins.append(float(top.values[0] - top.values[1]))
            frames.append(frame)
            token = int(top.indices[0])
            tokens.append(token)
            symbols = 0 if token == model.config.blank_token_id else symbols + 1
            if token == model.config.blank_token_id or symbols >= model.max_symbols_per_step:
                frame, symbols = frame+1, 0
            if len(tokens) > encoder.shape[1]*model.max_symbols_per_step:
                raise ValueError("unbounded fixture decode")
        result = {"encoder_rows": int(encoder.shape[1]), "lookahead": 3,
                  "prompt_id": model.config.default_prompt_id, "tokens": tokens, "frames": frames,
                  "selected_logits": selected_logits, "runner_tokens": runner_tokens,
                  "runner_logits": runner_logits, "top_two_margins": margins}
        (args.out / "asr_jfk_full_decode.json").write_text(json.dumps(result, indent=2) + "\n")
        print("steps", len(tokens), "nonblank", sum(x != model.config.blank_token_id for x in tokens),
              "min_top_two_margin", min(margins), "tokens", [x for x in tokens if x != model.config.blank_token_id])


if __name__ == "__main__":
    main()
