import { expect, test } from "bun:test";
import { codeOnly, inventory, scanSource } from "./profile-source";

test("lexical profiling ignores comments/literals and preserves line offsets", () => {
 const src='package p\n// make([]float32, 9)\nvar s = `math.Exp(x)\nappend(x,y)`\nfunc f(){\n x := make([]float32, 8)\n for i := range x { sum += math.Exp(float64(x[i])) }\n}\n';
 expect(codeOnly(src).split("\n").length).toBe(src.split("\n").length);
 const scanned=scanSource("model/p/a.go",src);
 expect(scanned.sites.map(s=>[s.line,s.kind])).toEqual([[6,"allocation-candidate"],[7,"scalar-math"],[7,"numeric-loop-candidate"]]);
 expect(scanned.loops).toBe(1);
});
test("inventory distinguishes missing tests, benchmarks and generated code",()=>{
 const result=inventory([
  {path:"model/p/a.go",source:"package p\nfunc f(){ x:=make([]float32,2);simd.Dot(x,x) }"},
  {path:"model/p/a_test.go",source:"func TestA(t *testing.T) {}\nfunc BenchmarkA(b *testing.B) {make([]int,9)}"},
  {path:"loader/q/a.go",source:"package q\nfunc f(){append(x,y)}"},
  {path:"generated/z.go",source:"// Code generated by x. DO NOT EDIT.\nfunc f(){make([]int,8)}"},
  {path:"ignored.txt",source:"make([]int,1)"},
 ]);
 expect(result.files.length).toBe(4);
 expect(result.packages.find(p=>p.path==="model/p")).toMatchObject({tests:1,benchmarks:1,allocationSites:1,simdCalls:1,testFiles:1});
 expect(result.packages.find(p=>p.path==="loader/q")).toMatchObject({tests:0,benchmarks:0,testFiles:0,allocationSites:1});
 expect(result.packages.find(p=>p.path==="generated")).toMatchObject({allocationSites:0});
});
