package k3

import "os"

var q4kScaledLoopOn = os.Getenv("IME2_Q4K_SCALED_LOOP") != "0"
var q4kLlamaZPOn = os.Getenv("IME2_Q4K_LLAMA_ZP") != ""
var q4kCompareOn = os.Getenv("IME2_Q4K_COMPARE") != ""
var q4kGoAsmSerialOn = os.Getenv("IME2_Q4K_GOASM_SERIAL") != ""
var q4kGoAsmOn = os.Getenv("IME2_Q4K_GOASM") != ""
var q4kCShimOn = os.Getenv("IME2_Q4K_CSHIM") != ""
var q4kLlamaX32RefOn = os.Getenv("IME2_Q4K_LLAMA_X32_REF") != ""
var q4kExactOn = os.Getenv("IME2_Q4K_EXACT") != ""
var q4kBatchOn = os.Getenv("IME2_Q4K_NO_BATCH") == ""
var q4kTCMBWaveOn = os.Getenv("IME2_TCM_B_WAVE") != ""
var q4kTCMBWaveSingleOn = os.Getenv("IME2_TCM_B_WAVE_SINGLE") != ""
var q4kTCMBWaveBatchOn = q4kTCMBWaveOn && os.Getenv("IME2_TCM_B_WAVE_BATCH") != "0"
var q4kTCMBWaveGateOn = q4kTCMBWaveOn && os.Getenv("IME2_TCM_B_WAVE_GATE") != "0"
var q4kGateFuseOn = os.Getenv("IME2_Q4K_GATE_FUSE") != "0"
var q4kFFNFuseOn = os.Getenv("IME2_Q4K_FFN_FUSE") != ""
var nativeI8I8On = os.Getenv("IME2_NATIVE_I8I8") != ""
var nativeI8I8WVOn = nativeI8I8On || os.Getenv("IME2_NATIVE_I8I8_WV") != ""
var nativeI8I8DownOn = nativeI8I8On || os.Getenv("IME2_NATIVE_I8I8_DOWN") != ""
var nativeI8I8LMOn = nativeI8I8On || os.Getenv("IME2_NATIVE_I8I8_LM") != ""
var int8DownAddOn = os.Getenv("IME2_INT8_DOWN_ADD") != "0"
var q8RoundOn = os.Getenv("IME2_Q8_ROUND") != "0"
var q8RVVOn = os.Getenv("IME2_Q8_RVV") != ""
var q4kNativeCGOOn = os.Getenv("IME2_Q4K_NATIVE_CGO") != ""
