// Package speechjob provides an opt-in durable store for sequential speech jobs.
// It does not load models, start workers/services, or choose inference defaults.
package speechjob

import (
	"context"
	"errors"
	"io"
	"time"
)

var (
	ErrBusy          = errors.New("speech job store is busy")
	ErrClosed        = errors.New("speech job store is closed")
	ErrLimit         = errors.New("speech job storage limit exceeded")
	ErrCorrupt       = errors.New("speech job artifact/manifest integrity failure")
	ErrConfiguration = errors.New("speech job configuration or stage identity changed")
	ErrPersistence   = errors.New("speech job durable publication failed or is uncertain")
)

// Limits are explicit positive caps. MaxBytes includes every store file,
// including orphaned crash artifacts; no automatic deletion reclaims space.
// Manifest and lock overhead count. MaxArtifactBytes/MaxUploadBytes are caps per
// payload, not an inference memory limit. One executor runs at a time per store.
type Limits struct {
	MaxJobs                                    int
	MaxUploadBytes, MaxArtifactBytes, MaxBytes int64
}

type Status string

const (
	Queued    Status = "queued"
	Running   Status = "running"
	Failed    Status = "failed"
	Cancelled Status = "cancelled"
	Complete  Status = "complete"
)

// Blob paths are generated by the store, never supplied as input filenames.
// Payload hashes, lengths, stage key and config identity are verified on reuse.
type Blob struct {
	File   string `json:"file"`
	SHA256 string `json:"sha256"`
	Bytes  int64  `json:"bytes"`
}
type Checkpoint struct {
	Stage   string `json:"stage"`
	Version string `json:"version"`
	Key     string `json:"key"`
	Blob    Blob   `json:"blob"`
}

// Manifest is a detached snapshot. Configuration is opaque nonsecret UTF-8 JSON
// retained byte-for-byte. Callers must include model/source revisions, precision,
// backend, frontend/timing, language/task and decoding options; the store cannot
// infer omitted semantics. A byte change means a different configuration.
type Manifest struct {
	Schema              int          `json:"schema"`
	ID                  string       `json:"id"`
	Name                string       `json:"name"`
	Configuration       string       `json:"configuration"`
	ConfigurationSHA256 string       `json:"configuration_sha256"`
	Input               Blob         `json:"input"`
	MediaReleased       bool         `json:"media_released,omitempty"`
	Status              Status       `json:"status"`
	Attempts            int          `json:"attempts"`
	ActiveStage         string       `json:"active_stage,omitempty"`
	Error               string       `json:"error,omitempty"`
	Created             time.Time    `json:"created"`
	Updated             time.Time    `json:"updated"`
	Checkpoints         []Checkpoint `json:"checkpoints"`
}

// Stage must write only its result to dst, honour cancellation, and return only
// after draining owned GPU/worker activity. The store cannot interrupt a stuck
// callback or an arbitrary blocking Reader. Panics become failed jobs. Version
// is a caller-provided SHA256 of the stage/model/options contract. A stage must
// produce byte-deterministic output for that identity; different bytes after a
// payload-publication crash are rejected without replacing the retained orphan.
// Nondeterministic inference/export must use a new configuration/job, not pretend
// to resume a deterministic checkpoint. The executor
// is deliberately serial: every preceding checkpoint is a dependency.
type Stage struct {
	Name    string
	Version string
	Run     func(context.Context, *Input, io.Writer) error
}

// Input exposes read-only verified snapshots to one stage. A callback owns and
// closes every reader it opens. Paths and writable checkpoint storage are not
// exposed. Keep readers within the callback lifetime.
type Input struct {
	store *Store
	job   Manifest
}

func (i *Input) Manifest() Manifest { return clone(i.job) }
func (i *Input) OpenSource(ctx context.Context) (io.ReadCloser, error) {
	return i.store.openBlob(ctx, i.job.ID, i.job.Input)
}
func (i *Input) OpenCheckpoint(ctx context.Context, stage string) (io.ReadCloser, error) {
	for _, cp := range i.job.Checkpoints {
		if cp.Stage == stage {
			return i.store.openBlob(ctx, i.job.ID, cp.Blob)
		}
	}
	return nil, errors.New("speech stage checkpoint not found")
}

// Progress reports committed state only; its optional callback is synchronous
// and must not block indefinitely. A callback panic is contained and ignored:
// reporting does not change job outcome. Context cancellation remains effective.
type Progress func(Manifest)
